# Generated by Django 4.2.7 on 2023-11-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zakaznew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adres', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=12)),
                ('total', models.IntegerField()),
                ('samzakaz', models.TextField()),
            ],
        ),
    ]
