# Generated by Django 4.2.7 on 2024-01-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_korzina_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='vkorzine',
            field=models.BooleanField(default=False),
        ),
    ]
